/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIdRouteImport } from './routes/supplier.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as AuthenticatedRequestProductRouteImport } from './routes/_authenticated/request-product'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedIncomingRouteImport } from './routes/_authenticated/incoming'
import { Route as AuthenticatedFinancingRouteImport } from './routes/_authenticated/financing'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCtrl7x9q2kRouteImport } from './routes/_authenticated/ctrl-7x9q2k'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIdRoute = SupplierIdRouteImport.update({
  id: '/supplier/$id',
  path: '/supplier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestProductRoute =
  AuthenticatedRequestProductRouteImport.update({
    id: '/request-product',
    path: '/request-product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomingRoute = AuthenticatedIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancingRoute = AuthenticatedFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCtrl7x9q2kRoute = AuthenticatedCtrl7x9q2kRouteImport.update({
  id: '/ctrl-7x9q2k',
  path: '/ctrl-7x9q2k',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/ctrl-7x9q2k': typeof AuthenticatedCtrl7x9q2kRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/financing': typeof AuthenticatedFinancingRoute
  '/incoming': typeof AuthenticatedIncomingRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/request-product': typeof AuthenticatedRequestProductRoute
  '/pay/return': typeof PayReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/supplier/$id': typeof SupplierIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/cart': typeof AuthenticatedCartRoute
  '/ctrl-7x9q2k': typeof AuthenticatedCtrl7x9q2kRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/financing': typeof AuthenticatedFinancingRoute
  '/incoming': typeof AuthenticatedIncomingRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/request-product': typeof AuthenticatedRequestProductRoute
  '/pay/return': typeof PayReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/supplier/$id': typeof SupplierIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/ctrl-7x9q2k': typeof AuthenticatedCtrl7x9q2kRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/financing': typeof AuthenticatedFinancingRoute
  '/_authenticated/incoming': typeof AuthenticatedIncomingRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/request-product': typeof AuthenticatedRequestProductRoute
  '/pay/return': typeof PayReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/supplier/$id': typeof SupplierIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/account'
    | '/cart'
    | '/ctrl-7x9q2k'
    | '/dashboard'
    | '/favorites'
    | '/financing'
    | '/incoming'
    | '/my-requests'
    | '/onboarding'
    | '/request-product'
    | '/pay/return'
    | '/product/$id'
    | '/supplier/$id'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/account'
    | '/cart'
    | '/ctrl-7x9q2k'
    | '/dashboard'
    | '/favorites'
    | '/financing'
    | '/incoming'
    | '/my-requests'
    | '/onboarding'
    | '/request-product'
    | '/pay/return'
    | '/product/$id'
    | '/supplier/$id'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/cart'
    | '/_authenticated/ctrl-7x9q2k'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/financing'
    | '/_authenticated/incoming'
    | '/_authenticated/my-requests'
    | '/_authenticated/onboarding'
    | '/_authenticated/request-product'
    | '/pay/return'
    | '/product/$id'
    | '/supplier/$id'
    | '/_authenticated/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  PayReturnRoute: typeof PayReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  SupplierIdRoute: typeof SupplierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$id': {
      id: '/supplier/$id'
      path: '/supplier/$id'
      fullPath: '/supplier/$id'
      preLoaderRoute: typeof SupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/request-product': {
      id: '/_authenticated/request-product'
      path: '/request-product'
      fullPath: '/request-product'
      preLoaderRoute: typeof AuthenticatedRequestProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incoming': {
      id: '/_authenticated/incoming'
      path: '/incoming'
      fullPath: '/incoming'
      preLoaderRoute: typeof AuthenticatedIncomingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financing': {
      id: '/_authenticated/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof AuthenticatedFinancingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ctrl-7x9q2k': {
      id: '/_authenticated/ctrl-7x9q2k'
      path: '/ctrl-7x9q2k'
      fullPath: '/ctrl-7x9q2k'
      preLoaderRoute: typeof AuthenticatedCtrl7x9q2kRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCtrl7x9q2kRoute: typeof AuthenticatedCtrl7x9q2kRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedFinancingRoute: typeof AuthenticatedFinancingRoute
  AuthenticatedIncomingRoute: typeof AuthenticatedIncomingRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRequestProductRoute: typeof AuthenticatedRequestProductRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCtrl7x9q2kRoute: AuthenticatedCtrl7x9q2kRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedFinancingRoute: AuthenticatedFinancingRoute,
  AuthenticatedIncomingRoute: AuthenticatedIncomingRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRequestProductRoute: AuthenticatedRequestProductRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  PayReturnRoute: PayReturnRoute,
  ProductIdRoute: ProductIdRoute,
  SupplierIdRoute: SupplierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
